// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelService.Data;

#nullable disable

namespace NovelService.Migrations
{
    [DbContext(typeof(NovelDbContext))]
    [Migration("20251030092719_AddDes")]
    partial class AddDes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NovelService.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NovelService.Models.Chapter", b =>
                {
                    b.Property<int>("chapter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("chapter_id"));

                    b.Property<int>("chapter_number")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("novelID")
                        .HasColumnType("int");

                    b.Property<int?>("series_Id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("word_count")
                        .HasColumnType("int");

                    b.HasKey("chapter_id");

                    b.HasIndex("novelID", "chapter_number")
                        .IsUnique()
                        .HasDatabaseName("IX_Chapter_Novel_ChapterNumber");

                    b.HasIndex("series_Id", "chapter_number")
                        .IsUnique()
                        .HasDatabaseName("IX_Chapter_Series_ChapterNumber");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.Property<int>("novel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("novel_Id"));

                    b.Property<string>("cover_images")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("/images/covers/default_cover.jpg");

                    b.Property<int>("novel_number")
                        .HasColumnType("int");

                    b.Property<int?>("series_Id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updated_at"));

                    b.HasKey("novel_Id");

                    b.HasIndex("series_Id", "novel_number")
                        .IsUnique()
                        .HasDatabaseName("IX_NovelSeries_Novel_ChapterNumber");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("NovelService.Models.NovelSeries", b =>
                {
                    b.Property<int>("series_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("series_Id"));

                    b.Property<int?>("ClassicSeriesseries_Id")
                        .HasColumnType("int");

                    b.Property<string>("artist")
                        .HasColumnType("longtext");

                    b.Property<string>("author")
                        .HasColumnType("longtext");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("cover_images")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("/images/covers/default_cover.jpg");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("created_at"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("note")
                        .HasColumnType("longtext");

                    b.Property<string>("series_title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updated_at"));

                    b.Property<Guid>("uploader_id")
                        .HasColumnType("char(36)");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("word_count")
                        .HasColumnType("int");

                    b.HasKey("series_Id");

                    b.HasIndex("ClassicSeriesseries_Id");

                    b.HasIndex("category_id");

                    b.HasIndex("status_id");

                    b.ToTable("novel_series", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("NovelService.Models.NovelStatus", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("statusId"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("statusId");

                    b.ToTable("Novel_Statuses");
                });

            modelBuilder.Entity("NovelService.Models.NovelTag", b =>
                {
                    b.Property<int>("novelTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("novelTagId"));

                    b.Property<int>("series_Id")
                        .HasColumnType("int");

                    b.Property<int>("tagID")
                        .HasColumnType("int");

                    b.HasKey("novelTagId");

                    b.HasIndex("tagID");

                    b.HasIndex("series_Id", "tagID")
                        .IsUnique();

                    b.ToTable("Novel_Tags");
                });

            modelBuilder.Entity("NovelService.Models.Tag", b =>
                {
                    b.Property<int>("tagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tagId"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("tagName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("tagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NovelService.Models.ClassicSeries", b =>
                {
                    b.HasBaseType("NovelService.Models.NovelSeries");

                    b.Property<string>("ISBN_10")
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN_13")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("edition")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("publish_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("publisher")
                        .HasColumnType("longtext");

                    b.ToTable("classic_series", (string)null);
                });

            modelBuilder.Entity("NovelService.Models.Chapter", b =>
                {
                    b.HasOne("NovelService.Models.Novel", "Novel")
                        .WithMany("Chapters")
                        .HasForeignKey("novelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NovelService.Models.NovelSeries", "TS")
                        .WithMany("Chapters")
                        .HasForeignKey("series_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Novel");

                    b.Navigation("TS");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.HasOne("NovelService.Models.NovelSeries", "NovelSeries")
                        .WithMany("Novel")
                        .HasForeignKey("series_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NovelSeries");
                });

            modelBuilder.Entity("NovelService.Models.NovelSeries", b =>
                {
                    b.HasOne("NovelService.Models.ClassicSeries", "ClassicSeries")
                        .WithMany()
                        .HasForeignKey("ClassicSeriesseries_Id");

                    b.HasOne("NovelService.Models.Category", "category")
                        .WithMany("NovelSeries")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovelService.Models.NovelStatus", "status")
                        .WithMany("NovelSeries")
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClassicSeries");

                    b.Navigation("category");

                    b.Navigation("status");
                });

            modelBuilder.Entity("NovelService.Models.NovelTag", b =>
                {
                    b.HasOne("NovelService.Models.NovelSeries", "NovelSeries")
                        .WithMany("NovelTags")
                        .HasForeignKey("series_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovelService.Models.Tag", "Tag")
                        .WithMany("NovelTags")
                        .HasForeignKey("tagID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NovelSeries");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NovelService.Models.ClassicSeries", b =>
                {
                    b.HasOne("NovelService.Models.NovelSeries", null)
                        .WithOne()
                        .HasForeignKey("NovelService.Models.ClassicSeries", "series_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NovelService.Models.Category", b =>
                {
                    b.Navigation("NovelSeries");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("NovelService.Models.NovelSeries", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Novel");

                    b.Navigation("NovelTags");
                });

            modelBuilder.Entity("NovelService.Models.NovelStatus", b =>
                {
                    b.Navigation("NovelSeries");
                });

            modelBuilder.Entity("NovelService.Models.Tag", b =>
                {
                    b.Navigation("NovelTags");
                });
#pragma warning restore 612, 618
        }
    }
}
