// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovelService.Data;

#nullable disable

namespace NovelService.Migrations
{
    [DbContext(typeof(NovelDbContext))]
    partial class NovelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NovelService.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("category_id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NovelService.Models.Chapter", b =>
                {
                    b.Property<int>("chapter_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("chapter_id"));

                    b.Property<int>("chapter_number")
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("novelID")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("word_count")
                        .HasColumnType("int");

                    b.HasKey("chapter_id");

                    b.HasIndex("novelID", "chapter_number")
                        .IsUnique()
                        .HasDatabaseName("IX_Chapter_Novel_ChapterNumber");

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.Property<int>("novel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("novel_Id"));

                    b.Property<string>("artist")
                        .HasColumnType("longtext");

                    b.Property<string>("author")
                        .HasColumnType("longtext");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("cover_images")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("/images/cover/default_cover.jpg");

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("note")
                        .HasColumnType("longtext");

                    b.Property<int>("status_id")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("updated_at")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("updated_at"));

                    b.Property<int>("uploader_id")
                        .HasColumnType("int");

                    b.Property<int>("views")
                        .HasColumnType("int");

                    b.Property<int>("word_count")
                        .HasColumnType("int");

                    b.HasKey("novel_Id");

                    b.HasIndex("category_id");

                    b.HasIndex("status_id");

                    b.ToTable("Novels");
                });

            modelBuilder.Entity("NovelService.Models.NovelStatus", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("statusId"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("statusId");

                    b.ToTable("Novel_Statuses");
                });

            modelBuilder.Entity("NovelService.Models.NovelTag", b =>
                {
                    b.Property<int>("novelTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("novelTagId"));

                    b.Property<int>("novelID")
                        .HasColumnType("int");

                    b.Property<int>("tagID")
                        .HasColumnType("int");

                    b.HasKey("novelTagId");

                    b.HasIndex("tagID");

                    b.HasIndex("novelID", "tagID")
                        .IsUnique();

                    b.ToTable("Novel_Tags");
                });

            modelBuilder.Entity("NovelService.Models.Tag", b =>
                {
                    b.Property<int>("tagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("tagId"));

                    b.Property<string>("tagName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("tagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("NovelService.Models.Chapter", b =>
                {
                    b.HasOne("NovelService.Models.Novel", "Novel")
                        .WithMany("Chapters")
                        .HasForeignKey("novelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Novel");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.HasOne("NovelService.Models.Category", "category")
                        .WithMany("Novels")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovelService.Models.NovelStatus", "status")
                        .WithMany("Novels")
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("status");
                });

            modelBuilder.Entity("NovelService.Models.NovelTag", b =>
                {
                    b.HasOne("NovelService.Models.Novel", "Novel")
                        .WithMany("NovelTags")
                        .HasForeignKey("novelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NovelService.Models.Tag", "Tag")
                        .WithMany("NovelTags")
                        .HasForeignKey("tagID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Novel");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("NovelService.Models.Category", b =>
                {
                    b.Navigation("Novels");
                });

            modelBuilder.Entity("NovelService.Models.Novel", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("NovelTags");
                });

            modelBuilder.Entity("NovelService.Models.NovelStatus", b =>
                {
                    b.Navigation("Novels");
                });

            modelBuilder.Entity("NovelService.Models.Tag", b =>
                {
                    b.Navigation("NovelTags");
                });
#pragma warning restore 612, 618
        }
    }
}
